name: Setup target Build Environment
description: Setup an ARM or x86_64 build environment

inputs:
  arch:
    default: x86_64
    required: false
  target:
    default: x86_64-unknown-linux-gnu
    required: false
  toolchain:
    default: stable
    required: false
  components:
    required: false

runs:
  using: composite
  steps:
    - if: inputs.arch != 'x86_64'
      name: Replace target string
      id: findandreplace
      uses: mad9000/actions-find-and-replace-string@5
      with:
        source: ${{ inputs.target }}
        find: "unknown-"
        replace: ""

    - if: inputs.arch != 'x86_64'
      name: Install dependencies (Raspberry Pi)
      shell: bash
      run: |
        sudo apt-get update && sudo apt-get install -y \
          curl \
          gcc-aarch64-linux-gnu \
          gcc-arm-linux-gnueabihf \
          git \
          "libc6:${{ inputs.arch }}" \
          "libgcc-s1:${{ inputs.arch }}" \
          musl-tools \
          pkg-config

    - if: inputs.target == 'x86_64-unknown-linux-gnu' || inputs.target == 'x86_64-unknown-linux-musl'
      name: Install dependencies (x86_64 linux)
      shell: bash
      run: |
        sudo apt-get update && sudo apt-get -y install curl musl-tools pkg-config

    - name: Install toolchain
      uses: dtolnay/rust-toolchain@v1
      with:
        toolchain: ${{ inputs.toolchain }}
        target: ${{ inputs.target }}
        components: ${{ inputs.components }}

    - uses: Swatinem/rust-cache@v2

    - if: inputs.arch != 'x86_64'
      name: Install Cross-Compile Support
      uses: junelife/gha-ubuntu-cross@v6
      with:
        arch: ${{ inputs.arch }}

    - if: inputs.arch != 'x86_64'
      name: Set environment variables
      shell: bash
      run: |
        echo "PKG_CONFIG_ALLOW_SYSTEM_LIBS=0" >> $GITHUB_ENV
        echo "PKG_CONFIG_DIR=/opt/" >> $GITHUB_ENV
        echo "PKG_CONFIG_LIBDIR=/opt/usr/lib/pkgconfig:/opt/usr/share/pkgconfig" >> $GITHUB_ENV
        echo "PKG_CONFIG_ALLOW_CROSS=1" >> $GITHUB_ENV
        if [[ ${{ inputs.arch }} == arm64 ]]; then
          echo "PKG_CONFIG_PATH=/usr/lib/${{ steps.findandreplace.outputs.value }}/pkgconfig" >> $GITHUB_ENV
          echo "CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER=${{ steps.findandreplace.outputs.value }}-gcc" >> $GITHUB_ENV
        fi
        if [[ ${{ inputs.arch }} == armhf ]]; then
          echo "PKG_CONFIG_PATH=/usr/lib/arm-linux-gnueabihf/pkgconfig" >> $GITHUB_ENV
          echo "CARGO_TARGET_ARMV7_UNKNOWN_LINUX_GNUEABIHF_LINKER=arm-linux-gnueabihf-gcc" >> $GITHUB_ENV
        fi
