name: Package Release
inputs:
  arch:
    required: false
  github_token:
    required: true
  features:
    required: false
  target:
    required: true
  runs_on:
    required: true

runs:
  using: composite
  steps:
    - uses: ./.github/actions/setup-target
      with:
        arch: ${{ inputs.arch }}
        target: ${{ inputs.target }}

    - name: Build
      shell: bash
      run: |
        cargo build --release --all --target ${{ inputs.target }} ${{ inputs.features }}

    - name: Compress (Unix)
      if: ${{ inputs.runs_on != 'windows-2022' }}
      shell: bash
      run: |
        zip -j cargo-espflash-${{ inputs.target }}.zip target/${{ inputs.target }}/release/cargo-espflash
        zip -j espflash-${{ inputs.target }}.zip target/${{ inputs.target }}/release/espflash

    - name: Compress (Windows)
      if: ${{ inputs.runs_on == 'windows-2022' }}
      shell: bash
      run: |
        7z a -tzip cargo-espflash-${{ inputs.target }}.zip ./target/${{ inputs.target }}/release/cargo-espflash.exe
        7z a -tzip espflash-${{ inputs.target }}.zip ./target/${{ inputs.target }}/release/espflash.exe

    - uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ inputs.github_token }}
        file: "*.zip"
        file_glob: true
        tag: ${{ github.ref }}
