name: Raspberry Pi CI

on:
  pull_request:
    branches:
      - main
  push:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

# Cancel any currently running workflows from the same PR, branch, or
# tag when a new workflow is triggered.
#
# https://stackoverflow.com/a/66336834
concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}

jobs:
  # --------------------------------------------------------------------------
  # Check

  check:
    name: Check
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: false
      matrix:
        board:
          - arch: arm64
            target: aarch64-unknown-linux-gnu
          - arch: armhf
            target: armv7-unknown-linux-gnueabihf

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-arm
        with:
          arch: ${{ matrix.board.arch }}
          target: ${{ matrix.board.target }}

      - run: cargo check --features=raspberry

  check-lib:
    name: Check (lib)
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: false
      matrix:
        board:
          - arch: arm64
            target: aarch64-unknown-linux-gnu
          - arch: armhf
            target: armv7-unknown-linux-gnueabihf

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-arm
        with:
          arch: ${{ matrix.board.arch }}
          target: ${{ matrix.board.target }}

      - run: cargo check --lib --no-default-features --features=raspberry

  msrv:
    name: Check MSRV
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: false
      matrix:
        board:
          - arch: arm64
            target: aarch64-unknown-linux-gnu
          - arch: armhf
            target: armv7-unknown-linux-gnueabihf

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-arm
        with:
          arch: ${{ matrix.board.arch }}
          target: ${{ matrix.board.target }}
          toolchain: "1.65"

      - run: cargo check --features=raspberry

  # --------------------------------------------------------------------------
  # Test

  test:
    name: Unit Tests
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: false
      matrix:
        board:
          - arch: arm64
            target: aarch64-unknown-linux-gnu
          - arch: armhf
            target: armv7-unknown-linux-gnueabihf

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-arm
        with:
          arch: ${{ matrix.board.arch }}
          target: ${{ matrix.board.target }}

      - run: cargo test --lib --features=raspberry

  # --------------------------------------------------------------------------
  # Lint

  clippy:
    name: Clippy
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: false
      matrix:
        board:
          - arch: arm64
            target: aarch64-unknown-linux-gnu
          - arch: armhf
            target: armv7-unknown-linux-gnueabihf

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-arm
        with:
          arch: ${{ matrix.board.arch }}
          target: ${{ matrix.board.target }}
          components: clippy

      - run: cargo clippy --features=raspberry -- -D warnings -A clippy::too_many_arguments
